version: 2.1


executors:
  node-executor:
    docker:
      - image: cimg/node:23.8.0


jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
        name: "Install dependencies"
        command: npm install 

  lint:
    executor: node-executor
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: npm install
      - run:
        name: Lint
        command: npm run lint


workflows:
  ci-workflow:
    jobs:
      - test
      - lint
