version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:23.8.0
    steps:
      - checkout
      - run:
        name: "Install dependencies"
        command: npm install 
  lint:
    executors:
      name: node-executor
    steps:
      - run:
        name: Install dependencies
        command: npm install
      - run:
        name: Lint
        command: npm run lint


workflows:
  ci-workflow:
    jobs:
      - test
      - lint
